version: 2

models:
  - name: staging
    config:
      materialized: table

  - name: intermediate
    config:
      materialized: dynamic_table
      on_configuration_change: apply
      target_lag: downstream
      snowflake_warehouse: VHOL_WH

  - name: analytical
    config:
      materialized: dynamic_table
      on_configuration_change: apply
      target_lag: 60 seconds
      snowflake_warehouse: VHOL_WH